# Generated by Django 4.2.11 on 2024-04-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_reason',
            field=models.CharField(blank=True, choices=[('reason1', 'Reason 1'), ('reason2', 'Reason 2'), ('reason3', 'Reason 3')], max_length=100, null=True),
        ),
    ]
