name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        export PYTHONPATH="${{ github.workspace }}/service"
        export DJANGO_SETTINGS_MODULE=service.field_service.settings
        python -m pytest --cov=service

    - name: Generate HTML coverage report
      run: |
        coverage html
        mv htmlcov/* ${{ github.workspace }}/htmlcov
